name: Turbo

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: pCYSl5EDgo/cat@master
        id: get_node_version
        with:
          path: .nvmrc
          trim: true

      - name: Use Node.js ${{ steps.get_node_version.outputs.text }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.get_node_version.outputs.text }}

      - name: Use Yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: yarn build
